import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

import 'package:carousel_slider/carousel_slider.dart';
import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:floating_search_bar/floating_search_bar.dart';
import 'package:flushbar/flushbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_full_pdf_viewer/full_pdf_viewer_scaffold.dart';
// import 'package:flutter_datetime_picker/flutter_datetime_picker.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:provider/provider.dart';
import 'package:random_string/random_string.dart';
import 'package:sekolah/bloc/bloc.dart';
import 'package:sekolah/bloc/page_bloc.dart';
import 'package:sekolah/models/models.dart';
import 'package:sekolah/services/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:sekolah/shared/shared.dart';
import 'package:sekolah/ui/widgets/widgets.dart';
import 'package:pdf/pdf.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:permission_handler/permission_handler.dart';
// import 'package:assets_audio_player/assets_audio_player.dart';

import 'package:pdf/widgets.dart' as pw;
// import 'package:multi_page_form/multi_page_form.dart';
part 'signin_page.dart';
part 'sign_up_page.dart';
part 'main_page.dart';
part 'wrapper.dart';
part 'splash_page.dart';
part 'home_page.dart';
part 'ppdb_siswa.dart';
part 'confirmation_ppdb.dart';
part 'success_ppdb_page.dart';
part 'kontak_page.dart';
part 'tentang_page.dart';
part 'pengumuman_page.dart';
part 'data_ppdb_page.dart';
part 'detail_ppdb_page.dart';
part 'success_konfirmasi_ppdb.dart';
part 'view_pdf_ppdb.dart';
part 'account_confirmation_page.dart';
part 'my_data_ppdb.dart';
part 'data_siswa.dart';
part 'pengumuman_admin.dart';
part 'akun_page.dart';
